# Generated by Django 2.0.5 on 2018-09-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('fees_in_lakhs', models.IntegerField()),
                ('gre_verbal', models.IntegerField()),
                ('gre_writing', models.IntegerField()),
                ('gre_quantitative', models.IntegerField()),
                ('gre_percentile', models.IntegerField()),
                ('toefl', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('grade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='sirname + first + last', max_length=50)),
                ('education', models.CharField(choices=[('be', 'Bachelor of Engineering'), ('btech', 'Bachelor of Technology'), ('bsc', 'Bachelor of Science')], max_length=40)),
                ('graduation_CGPA', models.DecimalField(decimal_places=3, help_text='Decimal upto 3', max_digits=4)),
                ('toefl', models.IntegerField(blank=True, null=True, verbose_name='TOEFL')),
                ('gre_writing', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='GRE writing')),
                ('gre_verbal', models.IntegerField(blank=True, null=True, verbose_name='GRE Verbal')),
                ('gre_quantitative', models.IntegerField(blank=True, null=True, verbose_name='GRE Quantitative')),
                ('gre_percentile', models.IntegerField(blank=True, null=True)),
                ('work_experience', models.IntegerField(default=0, help_text='In years')),
                ('Budget', models.IntegerField(help_text='In Lacs')),
                ('email', models.EmailField(default='2016preeti.singh@ves.ac.in', editable=False, max_length=254)),
            ],
        ),
    ]
