# Generated by Django 2.0.5 on 2018-09-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='sirname + first + last', max_length=50)),
                ('education', models.CharField(choices=[('be', 'Bachelor of Engineering'), ('btech', 'Bachelor of Technology'), ('bsc', 'Bachelor of Science')], max_length=40)),
                ('graduation_CGPA', models.DecimalField(decimal_places=3, help_text='Decimal upto 3', max_digits=4)),
                ('toefl', models.IntegerField(blank=True, null=True, verbose_name='TOEFL')),
                ('gre_writing', models.IntegerField(blank=True, null=True, verbose_name='GRE writing')),
                ('gre_verbal', models.IntegerField(blank=True, null=True, verbose_name='GRE Verbal')),
                ('gre_quantitative', models.IntegerField(blank=True, null=True, verbose_name='GRE Quantitative')),
                ('gre_percentile', models.IntegerField()),
                ('work_experience', models.IntegerField(default=0, help_text='In years')),
                ('Budget', models.IntegerField(help_text='In Lacs')),
            ],
        ),
    ]
