# Generated by Django 2.0.5 on 2018-09-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0001_initial'),
    ]

    operations = [
    ]
