# Generated by Django 2.0.5 on 2018-09-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gre_writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='GRE writing'),
        ),
    ]
