# Generated by Django 2.0.5 on 2018-09-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0002_auto_20180922_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_country',
            field=models.CharField(choices=[('all', 'all'), ('United States', 'United States '), ('United Kingdom', 'United Kingdom'), ('Switzerland', 'Switzerland'), ('Singapore', 'Singapore'), ('Canada', 'Canada'), ('Netherland', 'Netherland')], default='all', max_length=40),
        ),
    ]
