# Generated by Django 2.0.5 on 2018-09-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0002_auto_20180921_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='2016preeti.singh@ves.ac.in', max_length=254),
        ),
    ]
