# Generated by Django 2.0.5 on 2018-09-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gre_percentile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
