# Generated by Django 2.0.5 on 2018-09-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msguide', '0004_auto_20180921_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='2016preeti.singh@ves.ac.in', editable=False, max_length=254),
        ),
    ]
